### ISSUE TITLE
How to get logs into Kibana in local machine

### ISSUE THREAD

**Issue by DilanLivera** [DilanLivera/notes#11]
## Description

Create a note about getting logs into Kibana to help with debugging in a multi-service environment.

## Notes

- Install Elasticsearch

  Download Elasticsearch from [Elastic - Download Elasticsearch](https://www.elastic.co/downloads/elasticsearch). The download page includes the instructions for the installation process. After downloading, unzip the folder and run the _**elasticsearch.bat**_ file inside the bin folder. To do this, you can open a PowerShell window and go to the Elasticsearch files folder and run `bin\elasticsearch.bat`. Port `9200` is the default port for Elasticsearch. You can test if Elasticsearch is running by executing `Invoke-RestMethod http://localhost:9200` command in PowerShell. This should return some data about the Elasticsearch instance.

- Install Kibana

  Download Kibana from [Elastic - Download Kibana](https://www.elastic.co/downloads/kibana). After downloading Kibana, unzip the folder and open the _**config/kibana.yml**_ file. Goto the _**elasticsearch.hosts**_ section in the _**kibana.yml**_ file and uncomment the line. _**elasticsearch.hosts**_ array should include the URL of the Elasticsearch instance. Next, open a PowerShell window, go to the Kibana files folder, and run `bin\kibana.bat`. After Kibana loads up, you can go to `http://localhost:5601` to visit the Kibana display. Port `5602` is the default port for Kibana.

- Install Filebeat

  Download Filebeat from [Elastic - Download Filebeat](https://www.elastic.co/beats/filebeat). After downloading Filebeat, unzip the folder, and then you need to set the log file path/paths in the _**filebeat.yml**_ file. To set the paths, go to the `paths` section of the `type`(e.g. `filestream` or `log`) under `filebeat.inputs:`. We also need to set the `enabled` property to `true`(This property is located right above the `paths` property). Next, we need to uncomment the Elasticsearch URL in the `hosts` property of `output.elasticsearch:` section.

  _Note: Use a processor to get the properties such as `AppId` in the message to fields. Please find more information in [Elastic - Filebeat Reference [7.17]: Configure Filebeat: Filter and enhance data with processors](https://www.elastic.co/guide/en/beats/filebeat/current/filtering-and-enhancing-data.html) document_

  ```yaml
  ###################### Filebeat Configuration Example #########################

  # Removed for brevity

  # ============================== Filebeat inputs ===============================

  filebeat.inputs:
    # Each - is an input. Most options can be set at the input level, so
    # you can use different inputs for various configurations.
    # Below are the input specific configurations.

    # filestream is an input for collecting log messages from files.
    - type: filestream

      # Change to true to enable this input configuration.
      enabled: true

      # Paths that should be crawled and fetched. Glob based paths.
      paths:
        - c:\temp\logs\*.log

      processors:
        - decode_json_fields:
            fields: ['message']
            process_array: false
            max_depth: 1
            target: 'hkpf'
            overwrite_keys: true
            add_error_key: true

  # Removed for brevity

  # ================================== Outputs ===================================

  # Configure what output to use when sending the data collected by the beat.

  # ---------------------------- Elasticsearch Output ----------------------------
  output.elasticsearch:
    # Array of hosts to connect to.
    hosts: ['localhost:9200']
  # Removed for brevity
  ```

  After updating the _**filebeat.yml**_ file run the `install-service-filebeat.ps1` script in the root folder. Suppose script execution is disabled on your system. In that case, you need to set the execution policy for the current session to allow the script to run (Open a PowerShell window as administrator and run `PowerShell.exe -ExecutionPolicy UnRestricted -File .\install-service-filebeat.ps1.`).

- Restart Elasticsearch and Kibana. In PowerShell run `bin\elasticsearch.bat` and `bin\kibana.bat` commands in the respective locations to start Elasticsearch and Kibana.
- Start Filebeat. In PowerShell run `Start-Service filebeat` to start Filebeat.

  Update on 10/03/22: Today, I got the following error when I tried to start filebeat using the above command.

  ```powershell
  PS C:\elk_stack\filebeat> Start-Service filebeat
  Start-Service : Service 'filebeat (filebeat)' cannot be started due to the following error: Cannot open filebeat
  service on computer '.'.
  At line:1 char:1
  + Start-Service filebeat
  + ~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
     ServiceCommandException
      + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand
  ```

  I was able to get it started using the following command.

  ```powershell
  PS C:\elk_stack\filebeat> .\filebeat.exe -e
  ```

- Add an index pattern in Kibana.

  When you visit the Discover section in Kibana, you will be prompted to create an index pattern. Otherwise, in the left-hand navigation bar, go to Stack Management then Index Patterns under the Kibana section. You should see a list of available sources you can use to create the pattern. Click _**Create Index Pattern**_ to create the index pattern. E.g. of a pattern `filebeat*`. Now you should see the logs in the Discover section(assuming there are log files in the location you provided in the _**filebeat.yml**_).

## Resources

- [Elastic - Filebeat quick start: installation and configuration](https://www.elastic.co/guide/en/beats/filebeat/7.17/filebeat-installation-configuration.html)
- [Elastic - Filebeat: Modules: Elasticsearch module](https://www.elastic.co/guide/en/beats/filebeat/7.17/filebeat-module-elasticsearch.html)
- [Elastic - Download Filebeat](https://www.elastic.co/beats/filebeat)
- [Elastic - Download Logstash](https://www.elastic.co/downloads/logstash)
- [Elastic - Download Elasticsearch](https://www.elastic.co/downloads/elasticsearch)
- [Elastic - Download Kibana](https://www.elastic.co/downloads/kibana)
- [SYSCO Middleware Blog - Filebeat and Elasticsearch - Adding custom fields in filebeat.yml based on log file path](https://blog.sysco.no/data/analysis/Filebeat-and-Elasticsearch-custom-fields-by-logfile-path/)
- [Elastic blog - Structuring Elasticsearch data with grok on ingest for faster analytics](https://www.elastic.co/blog/structuring-elasticsearch-data-with-grok-on-ingest-for-faster-analytics)
- [Elastic - Filebeat Reference [7.17]: Configure Filebeat: Filter and enhance data with processors](https://www.elastic.co/guide/en/beats/filebeat/current/filtering-and-enhancing-data.html)
